services:
  - type: web
    name: secretvault-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CONNECTION_STRING
        sync: false  # You'll set this manually in Render dashboard